#!/usr/bin/env python3
"""Deterministically generate Envelope 0 interface metadata and fixtures."""
from __future__ import annotations
import argparse, json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; REGISTRY=ROOT/"schema"/"interfaces.json"; OUT=ROOT/"generated"
TYPES={"uint":1,"bytes16":2,"bounded_json":3,"bool":4,"record":5,
       "record_array":6,"nullable_bytes16":7,"nullable_uint":8}
FIXTURE_VALUES={"uint":0,"bytes16":"00"*16,"bounded_json":"7b7d",
                "bool":False,"record":{},"record_array":[],
                "nullable_bytes16":None,"nullable_uint":None}

def load():
 data=json.loads(REGISTRY.read_text(encoding="utf-8"))
 if data.get("format")!=1 or not isinstance(data.get("interfaces"),list): raise ValueError("unsupported registry")
 names=set()
 for interface in data["interfaces"]:
  if interface["name"] in names or not re.fullmatch(r"guide\.[a-z0-9.]+",interface["name"]): raise ValueError("invalid interface name")
  names.add(interface["name"])
  if not (0<interface["major"]<=65535 and 0<=interface["minor"]<=65535) or not re.fullmatch(r"/run/(?:guideos/(?:brokers|supervisor|installer)|guideos-storage)/[a-z0-9.-]+\.sock",interface["endpoint"]): raise ValueError("invalid interface version or endpoint")
  for group in ("operations","events"):
   codes=set(); item_names=set()
   for item in interface[group]:
    if item["code"] in codes or item["name"] in item_names or not 0<item["code"]<=65535: raise ValueError("invalid or duplicate code")
    codes.add(item["code"]); item_names.add(item["name"])
    if group=="operations":
     if item["retry"] not in ("none","idempotent") or type(item["cancellable"]) is not bool: raise ValueError("invalid operation policy")
     for descriptor in item["descriptors"]:
      if isinstance(descriptor,str):
       if not re.fullmatch(r"[a-z0-9-]+",descriptor): raise ValueError("invalid descriptor role")
      elif not (isinstance(descriptor,dict) and re.fullmatch(r"[a-z0-9-]+",descriptor.get("role","")) and type(descriptor.get("required")) is bool):
       raise ValueError("invalid descriptor role")
     for field_group in ("arguments","result"):
      keys=set()
      for field in item[field_group]:
       if field["key"] in keys or not 0<=field["key"]<=65535 or field["type"] not in TYPES or type(field["required"]) is not bool: raise ValueError("invalid field")
       keys.add(field["key"])
    else:
     keys=set()
     for field in item.get("body",[]):
      if field["key"] in keys or not 0<=field["key"]<=65535 or field["type"] not in TYPES or type(field["required"]) is not bool: raise ValueError("invalid event field")
      keys.add(field["key"])
 return data

def macro(value): return re.sub(r"[^A-Za-z0-9]","_",value).upper()
def cname(value): return re.sub(r"[^A-Za-z0-9]","_",value).lower()

def outputs(data):
 h=["/* Generated by tools/generate.py; do not edit. */","#ifndef GUIDE_IPC_INTERFACES_H","#define GUIDE_IPC_INTERFACES_H","#include <stddef.h>","#include <stdint.h>","","enum guide_ipc_field_type { GUIDE_IPC_FIELD_UINT=1, GUIDE_IPC_FIELD_BYTES16=2, GUIDE_IPC_FIELD_BOUNDED_JSON=3, GUIDE_IPC_FIELD_BOOL=4, GUIDE_IPC_FIELD_RECORD=5, GUIDE_IPC_FIELD_RECORD_ARRAY=6, GUIDE_IPC_FIELD_NULLABLE_BYTES16=7, GUIDE_IPC_FIELD_NULLABLE_UINT=8 };","struct guide_ipc_field_spec { uint16_t key; uint8_t type; uint8_t required; };","struct guide_ipc_operation_spec { const char *interface_name; const char *grant; uint16_t interface_major, interface_minor, operation; uint8_t cancellable, idempotent, descriptor_min, descriptor_max; const struct guide_ipc_field_spec *arguments; size_t argument_count; const struct guide_ipc_field_spec *results; size_t result_count; };","struct guide_ipc_event_spec { const char *interface_name; uint16_t interface_major, interface_minor, event; const struct guide_ipc_field_spec *body; size_t body_count; };","extern const struct guide_ipc_operation_spec guide_ipc_operations[];","extern const size_t guide_ipc_operation_count;","extern const struct guide_ipc_event_spec guide_ipc_events[];","extern const size_t guide_ipc_event_count;",""]
 c=['/* Generated by tools/generate.py; do not edit. */','#include "guide_ipc_interfaces.h"','']
 py=["# Generated by tools/generate.py; do not edit.","INTERFACES = {"]
 md=["# Generated Envelope 0 interface registry","","Generated from `schema/interfaces.json`; do not edit directly.",""]
 fixtures={"format":1,"valid":[],"invalid":[]}; op_rows=[]; event_rows=[]
 for interface in data["interfaces"]:
  stem=macro(interface["name"]); h += [f'#define {stem}_NAME "{interface["name"]}"',f'#define {stem}_MAJOR {interface["major"]}u',f'#define {stem}_MINOR {interface["minor"]}u',f'#define {stem}_ENDPOINT "{interface["endpoint"]}"']
  py.append(f'    {interface["name"]!r}: {{"major": {interface["major"]}, "minor": {interface["minor"]}, "endpoint": {interface["endpoint"]!r}, "operations": {{')
  md += [f'## `{interface["name"]}` {interface["major"]}.{interface["minor"]}',"",f'Endpoint: `{interface["endpoint"]}`',"","| Code | Operation | Grant | Retry | Descriptors |","| ---: | --- | --- | --- | --- |"]
  for op in interface["operations"]:
   opstem=f'{stem}_OP_{macro(op["name"])}'; base=cname(opstem); h.append(f'#define {opstem} {op["code"]}u')
   for section,prefix in (("arguments","ARG"),("result","RESULT")):
    fields=op[section]; arr=f'{base}_{section}'
    if fields:
     c.append(f'static const struct guide_ipc_field_spec {arr}[] = {{')
     for field in fields:
      h.append(f'#define {opstem}_{prefix}_{macro(field["name"])} {field["key"]}u')
      c.append(f'    {{{field["key"]}u, {TYPES[field["type"]]}u, {1 if field["required"] else 0}u}},')
     c.append('};')
    else: arr='NULL'
    op[f'_{section}_array']=arr
   descriptor_roles=[d if isinstance(d,str) else d["role"] for d in op["descriptors"]]
   descriptor_min=sum(1 for d in op["descriptors"] if isinstance(d,str) or d["required"])
   descriptor_max=len(op["descriptors"])
   op["_descriptor_min"]=descriptor_min; op["_descriptor_max"]=descriptor_max
   py.append(f'        {op["code"]}: '+repr({**{k:op[k] for k in ("name","grant","cancellable","retry","arguments","result")},"descriptors":descriptor_roles,"descriptor_min":descriptor_min,"descriptor_max":descriptor_max})+',')
   descriptor_text="none" if not descriptor_roles else f'{descriptor_min}..{descriptor_max} '+",".join(descriptor_roles)
   md.append(f'| {op["code"]} | `{op["name"]}` | `{op["grant"]}` | `{op["retry"]}` | `{descriptor_text}` |')
   fixtures["valid"].append({"interface":interface["name"],"operation":op["code"],"arguments":{str(f["key"]):FIXTURE_VALUES[f["type"]] for f in op["arguments"]}})
   op_rows.append((interface,op))
  py.append("    }, \"events\": {")
  if interface["events"]:
   md += ["","| Code | Event |","| ---: | --- |"]
  for event in interface["events"]:
   eventstem=f'{stem}_EVENT_{macro(event["name"])}'; base=cname(eventstem); h.append(f'#define {eventstem} {event["code"]}u')
   fields=event.get("body",[]); arr=f'{base}_body'
   if fields:
    c.append(f'static const struct guide_ipc_field_spec {arr}[] = {{')
    for field in fields:
     h.append(f'#define {eventstem}_BODY_{macro(field["name"])} {field["key"]}u')
     c.append(f'    {{{field["key"]}u, {TYPES[field["type"]]}u, {1 if field["required"] else 0}u}},')
    c.append('};')
   else: arr='NULL'
   py.append(f'        {event["code"]}: '+repr({"name":event["name"],"body":fields})+',')
   md.append(f'| {event["code"]} | `{event["name"]}` |')
   event_rows.append((interface,event,arr))
  py.append("    }},"); md.append("")
 c += ["","const struct guide_ipc_operation_spec guide_ipc_operations[] = {"]
 for interface,op in op_rows:
  a=op['_arguments_array']; r=op['_result_array']
  c.append(f'    {{"{interface["name"]}", "{op["grant"]}", {interface["major"]}u, {interface["minor"]}u, {op["code"]}u, {1 if op["cancellable"] else 0}u, {1 if op["retry"]=="idempotent" else 0}u, {op["_descriptor_min"]}u, {op["_descriptor_max"]}u, {a}, {len(op["arguments"])}u, {r}, {len(op["result"])}u}},')
 c += ["};","const size_t guide_ipc_operation_count = sizeof(guide_ipc_operations)/sizeof(guide_ipc_operations[0]);",""]
 c += ["const struct guide_ipc_event_spec guide_ipc_events[] = {"]
 for interface,event,arr in event_rows:
  c.append(f'    {{"{interface["name"]}", {interface["major"]}u, {interface["minor"]}u, {event["code"]}u, {arr}, {len(event.get("body",[]))}u}},')
 c += ["};","const size_t guide_ipc_event_count = sizeof(guide_ipc_events)/sizeof(guide_ipc_events[0]);",""]
 h += ["","#endif",""]; py += ["}",""]
 fixtures["invalid"]=[{"reason":"operation-zero","operation":0},{"reason":"unknown-field","operation":1,"arguments":{"31":0}}]
 return {OUT/"guide_ipc_interfaces.h":"\n".join(h),OUT/"guide_ipc_interfaces.c":"\n".join(c),OUT/"guide_ipc_interfaces.py":"\n".join(py),OUT/"INTERFACES.md":"\n".join(md),OUT/"fixtures.json":json.dumps(fixtures,indent=2,sort_keys=True)+"\n"}

def main():
 parser=argparse.ArgumentParser(); parser.add_argument("--check",action="store_true"); args=parser.parse_args(); generated=outputs(load()); failed=[]
 for path,content in generated.items():
  if args.check:
   if not path.exists() or path.read_text(encoding="utf-8")!=content: failed.append(str(path.relative_to(ROOT)))
  else: path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding="utf-8",newline="\n")
 if failed: raise SystemExit("generated output differs: "+", ".join(failed))
if __name__=="__main__": main()
