# Match only the native video decoder, before a stream is linked.
stream.rules = [
  {
    matches = [ { application.name = "GuideOS-Video" } ]
    actions = { update-props = {
      node.dont-reconnect = true
      node.dont-fallback = true
      node.stream.restore-target = false
    } }
  }
]
