LABEL GuideOS BRINGUP-0
  kernel /Image
  devicetree /allwinner/sun50i-h700-anbernic-rg35xx-h.dtb
  append root=PARTUUID=485e4ab2-4b05-4e68-877f-df6af64f3918 rootwait rootfstype=ext4 console=tty0 console=ttyS0,115200 panic=10
