wireplumber.profiles = {
  main = {
    monitor.bluez.seat-monitoring = disabled
    monitor.v4l2 = disabled
    monitor.libcamera = disabled
  }
}
monitor.bluez.properties = {
  bluez5.roles = [ a2dp_source ]
  bluez5.codecs = [ sbc ]
}
